name: auth_demo
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.2
  firebase_core:
  firebase_auth:
  cloud_firestore:
  firebase_storage:
  firebase_messaging: ^15.2.4
  firebase_crashlytics:
  cloud_functions:
  google_sign_in: ^6.2.2
  provider:
  intl:
  image_picker:
  google_fonts:
  cached_network_image:
  flutter_easyloading:
  go_router:
  flutter_rating_bar:
  freezed_annotation:
  json_annotation:
  firebase_core_web: ^2.12.1
  google: ^0.0.1
  flutter_toast_message_bar: ^0.0.8
  fluttertoast: ^8.2.12
  flutter_svg: ^2.0.17
  smooth_page_indicator: ^1.2.1
  carousel_slider: ^4.2.1
  flutter_screenutil: ^5.9.3
  onesignal_flutter: ^5.3.0
  path: ^1.9.1
  path_provider: ^2.1.5
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices.
  flutter_lints: ^2.0.0
  freezed:
  json_serializable:
  build_runner:
  flutter_launcher_icons: ^0.14.3

# Configuration for flutter_launcher_icons
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/food-delivery.png"

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # Add your assets here
  assets:
    - assets/images/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700