// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTBPbnwIMUFlPHhQq4HIO_ZFKVdL8Fxqk',
    appId: '1:191730222733:web:409faed19b867e53e704c4',
    messagingSenderId: '191730222733',
    projectId: 'foodapp-8db9c',
    authDomain: 'foodapp-8db9c.firebaseapp.com',
    storageBucket: 'foodapp-8db9c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn_PobWTneB09kWlJYMNSy7aK38l4mM1w',
    appId: '1:191730222733:android:dff6cdbab5884a4be704c4',
    messagingSenderId: '191730222733',
    projectId: 'foodapp-8db9c',
    storageBucket: 'foodapp-8db9c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs5RQHenXN1h5S8JSv-xvMw7TZhQ-awUQ',
    appId: '1:191730222733:ios:c07b58fa920cc5f3e704c4',
    messagingSenderId: '191730222733',
    projectId: 'foodapp-8db9c',
    storageBucket: 'foodapp-8db9c.firebasestorage.app',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs5RQHenXN1h5S8JSv-xvMw7TZhQ-awUQ',
    appId: '1:191730222733:ios:c07b58fa920cc5f3e704c4',
    messagingSenderId: '191730222733',
    projectId: 'foodapp-8db9c',
    storageBucket: 'foodapp-8db9c.firebasestorage.app',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTBPbnwIMUFlPHhQq4HIO_ZFKVdL8Fxqk',
    appId: '1:191730222733:web:d52ad6076a920dbae704c4',
    messagingSenderId: '191730222733',
    projectId: 'foodapp-8db9c',
    authDomain: 'foodapp-8db9c.firebaseapp.com',
    storageBucket: 'foodapp-8db9c.firebasestorage.app',
  );
}
